In [3]:
import pymongo
import pandas as pd
import tensorflow_hub as hub
import numpy as np
from tqdm import tqdm
from pymongo import MongoClient

In [4]:
client = MongoClient('mongodb+srv://omkar_eazr:242424@eazr.jzaia.mongodb.net/eazr_test?retryWrites=true&w=majority')
db = client.eazr_test
table = db.testdevicedetails

# Temp

In [ ]:
# import json
# from pprint import pprint
# from bson import json_util
# for device in table.find():
#     if device['uniqueId']=='789b938851841fe8':
#         with open('newdata1.json', 'w') as f:
#             f.write(json_util.dumps(device))

In [5]:
sms_corpus = []
for doc in table.find():
    try:
        sms_corpus.extend(doc['sms'])
    except:
        pass

In [6]:
sms_corpus[0]

{'_id': 48,
 'thread_id': 10,
 'address': 'JD-620016',
 'date': 1620892349013,
 'date_sent': 1620892346000,
 'protocol': 0,
 'read': 0,
 'status': -1,
 'type': 1,
 'reply_path_present': 0,
 'body': 'Rs.129 प्लान से आपको 28 दिनों के लिए असीमित कॉल्स और 2 जीबी डेटा मिलता है । रिचार्ज करने के लिए क्लिक करें www.jio.com/r/p2UsxTsPI T&C',
 'service_center': '+917012075009',
 'locked': 0,
 'error_code': 0,
 'seen': 0,
 'timed': 0,
 'deleted': 0,
 'sync_state': 0,
 'marker': 0,
 'bind_id': 0,
 'mx_status': 0,
 'out_time': 0,
 'sim_id': 3,
 'block_type': 0,
 'advanced_seen': 1,
 'b2c_ttl': 0,
 'fake_cell_type': 0,
 'url_risky_type': 0,
 'favorite_date': 0}

In [7]:
data = pd.DataFrame(sms_corpus)

In [8]:
data.columns

Index(['_id', 'thread_id', 'address', 'date', 'date_sent', 'protocol', 'read',
       'status', 'type', 'reply_path_present', 'body', 'service_center',
       'locked', 'error_code', 'seen', 'timed', 'deleted', 'sync_state',
       'marker', 'bind_id', 'mx_status', 'out_time', 'sim_id', 'block_type',
       'advanced_seen', 'b2c_ttl', 'fake_cell_type', 'url_risky_type',
       'favorite_date', 'mx_id_v2', 'b2c_numbers', 'sub_id', 'phone_id',
       'creator', 'priority', 'pri', 'lgeMsgType', 'doInstalled',
       'sms_imsi_data', 'group_id', 'ui_duplicate', 'dcs', 'original_address',
       'confirm_read', 'simcopy', 'save_call_type', 'msg_boxtype', 'modified',
       'modified_time', 'reply_option', 'sms_format', 'spam_report',
       'reserve_time', 'chatting_read_reply', 'kpas_messageid',
       'kpas_serialnumber', 'insert_time', 'textlink', 'message_class',
       'reference_number', 'c0_iei', 'kt_is_tm', 'kt_tm_type', 'person',
       'rcs_extra', 'rcs_timestamp_delivered', 'rcs_

In [9]:
sms_df = data[['address', 'date','body']]

In [10]:
sms_df

address           date  \
0      JD-620016  1620892349013   
1      JX-620016  1620645472998   
2      JM-620016  1620281773874   
3      JK-620016  1620037178888   
4      JX-620016  1619687440775   
...          ...            ...   
25474  TM-PHONPE  1562227082898   
25475  TM-PHONPE  1562227067681   
25476  JG-JIONET  1562225426709   
25477  JG-JioPay  1562225424082   
25478  JG-JIOSVC  1562225416248   

                                                    body  
0      Rs.129 प्लान से आपको 28 दिनों के लिए असीमित कॉ...  
1      Rs.129 Plan gives you 2GB data, Unlimited Voic...  
2      Rs.129 प्लान से आपको 28 दिनों के लिए असीमित कॉ...  
3      Rs.129 Plan gives you 2GB data, Unlimited Voic...  
4      Rs.129 प्लान से आपको 28 दिनों के लिए असीमित कॉ...  
...                                                  ...  
25474  83253 is your one time password to proceed on ...  
25475  39555 is your one time password to proceed on ...  
25476  Congratulations! You have received coupons fro...  
25477  आपके जियो नंबर 7977491939 पर Rs. 399.0 का रिचा...  
25478  Recharge of Rs. 399.0 is successful for your J...  

[25479 rows x 3 columns]

In [ ]:
import regex as re


class Transaction_Extractor:
    # Extract Account no
    def account_no_extractor(self, msg):
        account_patn = r'([Xx\*]+|(\.\.)+)\d{3,5}'
        if re.search(account_patn, msg):
            account_no = re.search(account_patn, msg).group()
            return account_no
        else:
            return np.nan

    # Extract dates from messages
    def date_extractor(self, msg):
        # regex1 = "\d+/\d+/\d+"
        # date_patn = '(\d+\s*(\-|\/)\s*(\w+|\d+)\s*(\|\/)\s*(\d+)\s*(\d*\:\d+\:\d+)*)'
        # date_patn = '\d+[-/]\d+[-/]\d+'
        date_patn = re.compile(r'(\d+[/-]\d+[-/]\d+)|(\d+?[-\s]?(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|january|february|march|april|may|june|july|august|september|october|november|december)[-\s]?\d+)', re.IGNORECASE)
        # match = re.search(r'\d{2}-\d{2}-\d{4}',msg.msg)
        try:
            match = re.search(date_patn, msg)
            date = match.group()
            # print(date)
            return date
        except:
            return np.nan

    # Amount extractor
    def amount_extractor(self, msg):
        # reg = '(?i)(?:(?:RS|INR|MRP)\.?\s?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)'

        credit_patterns = [
            r'((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)\s(credited\sto)',
            r'(is\scredited\s|credited\sby\s|credited\sfor\s)((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)'
        ]

        debit_patterns = [
            r'((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)\s(has\sbeen\sdebited\sfrom|was\sdebited)',
            r'(debited\sby\s|debited\sfor\s|debited\swith\s)((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)',
            r'((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)\s(withdrawn)',
            r'(Rs.?\s?+?)'
        ]

        credit_card_debit = [
            r'((Rs.|INR\s?)(\s+)?)(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)\s(was\sspent\son\syour\s[Cc]redit[Cc]ard)',
            r'(Transaction\sof\s)(Rs.?\s+?\d+.?\d+?)\shas\sbeen\smade'
        ]

        try:
            self.transaction_type = None
            for pattern in credit_patterns:
                amount = re.search(pattern, msg)              
                if amount:
                    money = re.search(r'(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)', amount.group())
                    money = re.sub(',', '', money.group())
                    self.transaction_type = 'credit'
                    return float(money)
            
            for pattern in debit_patterns:
                amount = re.search(pattern, msg)              
                if amount:
                    money = re.search(r'(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)', amount.group())
                    money = re.sub(',', '', money.group())
                    self.transaction_type = 'debit'
                    return float(money)
            
            for pattern in credit_card_debit:
                amount = re.search(pattern, msg)              
                if amount:
                    money = re.search(r'(\d+(:?\,\d+)?(\,\d+)?(\.\d{1,3})?)', amount.group())
                    money = re.sub(',', '', money.group())
                    self.transaction_type = 'ccdebit'
                    return float(money)
                
        except Exception as e:
            return np.nan
            # print('Message does not have any amount in it')

    # Type Extractor
    def credit_or_debit(self, msg):
        return self.transaction_type

    def extract(self, msg):
        data = {
            'Acc_No': self.account_no_extractor(msg),
            'Date': self.date_extractor(msg),
            'Amount': self.amount_extractor(msg),
            'Type': self.credit_or_debit(msg),
        }
        # print(data)
        return data

In [ ]:
extractor = Transaction_Extractor()
extracted = []
for i in range(len(sms_df)):
    temp = extractor.extract(sms_df.iloc[i]['body'])
    temp['address'] = sms_df.iloc[i]['address']
    temp['sms'] = sms_df.iloc[i]['body']
    extracted.append(temp)

In [ ]:
newdf = pd.DataFrame(extracted)
newdf = newdf.dropna()
newdf = newdf[['sms', 'Type']]
newdf.shape

(530, 2)

# Adding other topics for classifications

In [ ]:
app = pd.read_csv('/content/APPs_MSGs_DATA.csv')
app = app[['MSGBODY', 'TYPE']]
app.columns = ['sms', 'Type']
app.shape

(564, 2)

In [ ]:
final = pd.concat([newdf, app])
final.shape

(1094, 2)

# Label Encode

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# newdf['Type'] = le.fit_transform(final['Type'])

In [ ]:
# newdf.to_csv('newdf.csv', index=False)
# newdf

In [ ]:
# temp1 = newdf[newdf['Type'] == 'debit']
# temp2 = newdf[newdf['Type'] == 'credit']
# # temp3 = newdf[newdf['Type'] == 'ccdebit']
# final = pd.concat([temp1, temp2])
# final

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(final, random_state=42, test_size=0.05)
X_val, X_test = train_test_split(X_test, test_size=0.5)

In [ ]:
X_train, X_val, X_test

(                                                     sms                    Type
 15413  Dear SBI UPI User, ur A/cX5539 credited by Rs3...                  credit
 4647   Your a/c no. XXXXXXXX0691 is credited by Rs.15...                  credit
 86     Youve received Rs.145 cashback from PhonePe in...  phonepe_cashbackcredit
 12     Youve received Rs.15 from Er Aditya Giri via P...         phonepe_ credit
 328    Your Jio recharge of Rs 1250 through Mobikwik ...          mobikwik_debit
 ...                                                  ...                     ...
 8004   Dear Customer, Your account no ********6210 is...                   debit
 15460  Dear SBI UPI User, ur A/cX5539 credited by Rs1...                  credit
 5030   Acct XX605 debited with INR 45,000.00 on 02-No...                   debit
 514    You've paid Rs.4773 to Schemist via PhonePe fr...           phonepe_debit
 330    Your Jio recharge of Rs 850 through Mobikwik i...          mobikwik_debit
 
 [1039 rows x 

In [ ]:
from sklearn.utils import class_weight
class_weights = list(class_weight.compute_class_weight('balanced',
                                                       np.unique(final.Type),
                                                       final.Type))

In [ ]:
list(final.Type.value_counts().index)

['debit',
 'paytm_debit',
 'phonepe_debit',
 'credit',
 'mobikwik_debit',
 'phonepe_ credit',
 'phonepe_cashbackcredit']

In [ ]:
class_weights.sort()
class_weights

[0.3643023643023643,
 0.6795031055900621,
 0.7775408670931059,
 1.5473833097595473,
 3.473015873015873,
 3.551948051948052,
 3.551948051948052]

In [ ]:
weights = {}
for index, weight in enumerate(class_weights):
    weights[index] = weight
weights

{0: 0.3643023643023643,
 1: 0.6795031055900621,
 2: 0.7775408670931059,
 3: 1.5473833097595473,
 4: 3.473015873015873,
 5: 3.551948051948052,
 6: 3.551948051948052}

In [ ]:
X_train.shape, X_test.shape, X_val.shape

((1039, 2), (28, 2), (27, 2))

In [ ]:
dataset_train = tf.data.Dataset.from_tensor_slices((X_train['sms'].values, X_train['Type'].values))
dataset_test = tf.data.Dataset.from_tensor_slices((X_test['sms'].values, X_test['Type'].values))
dataset_val = tf.data.Dataset.from_tensor_slices((X_val['sms'].values, X_val['Type'].values))

In [ ]:
for text, target in dataset_train.take(5):
    print(f"Message: {text}, Type: {target}")
print()
for text, target in dataset_test.take(10):
    print(f"Message: {text}, Type: {target}")
print()
for text, target in dataset_val.take(5):
    print(f"Message: {text}, Type: {target}")

Message: b'Dear SBI UPI User, ur A/cX5539 credited by Rs30 on 28Jan21 by  (Ref no 102812210525)', Type: b'credit'
Message: b'Your a/c no. XXXXXXXX0691 is credited by Rs.15,000.00 on 02-Dec-2019 12:13:55 by a/c linked to mobile XXXXXXX298. (IMPS Ref no 933612686458).', Type: b'credit'
Message: b'Youve received Rs.145 cashback from PhonePe into your wallet for Get up to 100 Cashback. Flat 50 on first two transaction on IRCTC Android App.  Current cashback gift voucher balance is Rs.160', Type: b'phonepe_cashbackcredit'
Message: b'Youve received Rs.15 from Er Aditya Giri via PhonePe for txn P186255651918209. Download PhonePe Business App: https://phon.pe/ppb', Type: b'phonepe_ credit'
Message: b'Your Jio recharge of Rs 1250 through Mobikwik is successful. Available Balance : Rs 603. Not you? Raise concern bit.ly/helptct.', Type: b'mobikwik_debit'

Message: b'Rs.1.00 has been debited from your a/c no XXXX564490 on 01-02-21 towards UPI ID gadgemilind10-1@oksbi. To report fraud or raise disp

In [ ]:
table = tf.lookup.StaticHashTable(
    initializer = tf.lookup.KeyValueTensorInitializer(
        keys = tf.constant(['debit',
                            'paytm_debit',
                            'phonepe_debit',
                            'credit',
                            'mobikwik_debit',
                            'phonepe_ credit',
                            'phonepe_cashbackcredit']),
        values = tf.constant([0, 1, 2, 3, 4, 5, 6]),
    ),
    default_value = tf.constant(-1),
    name = 'target_encoding'
)

@tf.function
def target(x):
    return table.lookup(x)

In [ ]:
def show_batch(dataset, size=5):
    for batch, label in dataset.take(size):
        print(batch.numpy())
        print(target(label))

show_batch(dataset_test, 100)

b'Rs.1.00 has been debited from your a/c no XXXX564490 on 01-02-21 towards UPI ID gadgemilind10-1@oksbi. To report fraud or raise dispute, click kotak.com/fraud'
tf.Tensor(0, shape=(), dtype=int32)
b'Dear Customer, your Account XX5605 has been debited with INR 1,000.00 on 17-Jan-19. Info: BIL*ONL*001621951835*Standar. The Available Balance is INR 1,811.02.For dispute,call 04033667777.'
tf.Tensor(0, shape=(), dtype=int32)
b'Rs. 345  transferred to 9544347259 at 11:34 PM. Transaction ID 26628504131 , Updated Balance Paytm Wallet- Rs702'
tf.Tensor(1, shape=(), dtype=int32)
b'Rs. 470 transferred to 7839049039 at 2020-03-26 15:28:41. Updated Balance Rs. 423 For queries, visit http://m.p-y.tm/care '
tf.Tensor(1, shape=(), dtype=int32)
b"You've paid Rs.4700 to Vgarage via PhonePe from your CBI Bank  account."
tf.Tensor(2, shape=(), dtype=int32)
b'Dear Customer, Your a/c no. XXXXXXXX5605 is credited by Rs.2,000.00 on 12-Mar-2020 16:12:46 by a/c linked to mobile XXXXX36090. (IMPS Ref no 0072168

In [ ]:
def fetch(text, labels):
    return text, tf.one_hot(target(labels), 7)

In [ ]:
training_data = dataset_train.map(fetch)
testing_data = dataset_test.map(fetch)

In [ ]:
next(iter(testing_data.batch(11)))

(<tf.Tensor: shape=(11,), dtype=string, numpy=
 array([b'Rs.1.00 has been debited from your a/c no XXXX564490 on 01-02-21 towards UPI ID gadgemilind10-1@oksbi. To report fraud or raise dispute, click kotak.com/fraud',
        b'Dear Customer, your Account XX5605 has been debited with INR 1,000.00 on 17-Jan-19. Info: BIL*ONL*001621951835*Standar. The Available Balance is INR 1,811.02.For dispute,call 04033667777.',
        b'Rs. 345  transferred to 9544347259 at 11:34 PM. Transaction ID 26628504131 , Updated Balance Paytm Wallet- Rs702',
        b'Rs. 470 transferred to 7839049039 at 2020-03-26 15:28:41. Updated Balance Rs. 423 For queries, visit http://m.p-y.tm/care ',
        b"You've paid Rs.4700 to Vgarage via PhonePe from your CBI Bank  account.",
        b'Dear Customer, Your a/c no. XXXXXXXX5605 is credited by Rs.2,000.00 on 12-Mar-2020 16:12:46 by a/c linked to mobile XXXXX36090. (IMPS Ref no 007216855356).',
        b'Paid Rs.459  to KANCHAN COSMETICS STORE at 2020-09-02 18:27:

In [ ]:
train_data, train_labels = next(iter(training_data.batch(5)))
train_data, train_labels

(<tf.Tensor: shape=(5,), dtype=string, numpy=
 array([b'Dear SBI UPI User, ur A/cX5539 credited by Rs30 on 28Jan21 by  (Ref no 102812210525)',
        b'Your a/c no. XXXXXXXX0691 is credited by Rs.15,000.00 on 02-Dec-2019 12:13:55 by a/c linked to mobile XXXXXXX298. (IMPS Ref no 933612686458).',
        b'Youve received Rs.145 cashback from PhonePe into your wallet for Get up to 100 Cashback. Flat 50 on first two transaction on IRCTC Android App.  Current cashback gift voucher balance is Rs.160',
        b'Youve received Rs.15 from Er Aditya Giri via PhonePe for txn P186255651918209. Download PhonePe Business App: https://phon.pe/ppb',
        b'Your Jio recharge of Rs 1250 through Mobikwik is successful. Available Balance : Rs 603. Not you? Raise concern bit.ly/helptct.'],
       dtype=object)>, <tf.Tensor: shape=(5, 7), dtype=float32, numpy=
 array([[0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1

# Embedding Layer

In [ ]:
embedding = "https://tfhub.dev/google/nnlm-en-dim128/2"
hub_layer = hub.KerasLayer(embedding, output_shape=[128],
                           input_shape=[], dtype=tf.string, trainable=True)

In [ ]:
hub_layer(train_data[:1])

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-0.082191  ,  0.00647716, -0.05444428, -0.21686393,  0.14497133,
         0.00133491, -0.15317693, -0.12429048,  0.18104264,  0.1452226 ,
        -0.11405838,  0.20126656, -0.00442542, -0.10805954, -0.04318812,
        -0.1211186 , -0.02520508, -0.12278181, -0.01406656,  0.13421367,
         0.02047809,  0.11405487,  0.04405945, -0.06429577, -0.08660085,
        -0.27316344,  0.00583798, -0.04272067, -0.02662076,  0.04803495,
         0.03558242,  0.1319707 , -0.05097763, -0.09617107,  0.16551721,
        -0.03688629,  0.06484939, -0.05238657,  0.00230488,  0.17360702,
         0.01627862, -0.04907573,  0.01247564,  0.15568265,  0.08691856,
         0.00811548, -0.05884064, -0.0423116 , -0.07032693, -0.10783222,
        -0.10240479,  0.11876303, -0.0966095 , -0.00977529, -0.02423827,
        -0.03341391, -0.00665669, -0.06619374,  0.0574878 ,  0.09773885,
        -0.05910502, -0.05771718,  0.00062356,  0.01830241, -0.04260935,
 

In [ ]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Reshape(target_shape=(128, 1)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(.2))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dropout(.2))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dropout(.2))
model.add(tf.keras.layers.Dense(7, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 128)               124642688 
_________________________________________________________________
reshape (Reshape)            (None, 128, 1)            0         
_________________________________________________________________
bidirectional (Bidirectional (None, 128, 256)          133120    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 128)               164352    
_________________________________________________________________
dense (Dense)                (None, 128)               16512     
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8

In [ ]:
model.compile(optimizer='adam',
              loss = tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['acc'])

In [ ]:
training_data = training_data.shuffle(7000).batch(32)
testing_data = testing_data.batch(32)

In [ ]:
history = model.fit(training_data,
                    epochs=50,
                    validation_data=testing_data,
                    verbose=1, 
                    class_weight=weights
)

Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.


Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.


Epoch 1/50


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4870: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`categorical_crossentropy` received `from_logits=True`, but '


33/33 [==============================] - 15s 241ms/step - loss: 1.8706 - acc: 0.1213 - val_loss: 1.7664 - val_acc: 0.2143
Epoch 2/50
33/33 [==============================] - 6s 190ms/step - loss: 1.0853 - acc: 0.4321 - val_loss: 0.7511 - val_acc: 0.5714
Epoch 3/50
33/33 [==============================] - 6s 191ms/step - loss: 0.5287 - acc: 0.6554 - val_loss: 0.3641 - val_acc: 0.9286
Epoch 4/50
33/33 [==============================] - 6s 193ms/step - loss: 0.3675 - acc: 0.8633 - val_loss: 0.2133 - val_acc: 0.9286
Epoch 5/50
33/33 [==============================] - 6s 190ms/step - loss: 0.2734 - acc: 0.9134 - val_loss: 0.1413 - val_acc: 0.9643
Epoch 6/50
33/33 [==============================] - 6s 191ms/step - loss: 0.1841 - acc: 0.9384 - val_loss: 0.2002 - val_acc: 0.9286
Epoch 7/50
33/33 [==============================] - 6s 190ms/step - loss: 0.1332 - acc: 0.9490 - val_loss: 0.2877 - val_acc: 0.9286
Epoch 8/50
33/33 [==============================] - 6s 190ms/step - loss: 0.1316 - acc

In [ ]:
len(list(dataset_val))

27

In [ ]:
results = model.evaluate(dataset_val.map(fetch).batch(27), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))

1/1 - 0s - loss: 0.1341 - acc: 0.9259
loss: 0.134
acc: 0.926


In [ ]:
examples = ['Dear Customer, your Account XX5605 has been debited with INR 4,700.00 on 11-Feb-19. Info: BIL*ONL*001640199809*Citiban. The Available Balance is INR 21,147.12.For dispute,call 04033667777.',
            'Rs. 2.00 credited to a/c XXXXXX5024 on 16-04-21 by a/c linked to VPA goog-payment@okaxis (UPI Ref No  110620154923).',
            'Acct XX605 debited with INR 12,159.00 on 04-Oct-19.Info: ACH*HDBFINANC.Avbl Bal:INR 1,02,356.71.Call 18002662 for dispute or SMS BLOCK 605 to 9215676766',
            'Youve received Rs.88 cashback from PhonePe into your wallet for Get up to 100 Cashback. Flat 50 on first two transaction on IRCTC Android App.  Current cashback gift voucher balance is Rs.131',
            'Rs. 234 transferred to 9730815322 at 2021-02-03 15:28:41. Updated Balance Rs. 646 For queries, visit http://m.p-y.tm/care ',
            'Paid Rs.434  to SANIKA chosmetics STORE at 2021-02-10 18:27:06 . Order ID: 201908240451838 . Updated Balance: Paytm Wallet- Rs 1218',
            'Your Jio recharge of Rs 49 through Mobikwik is successful. Available Balance : Rs 521. Not you? Raise concern bit.ly/helptct.',
            'Youve received Rs.127 from Er Aditya Giri via PhonePe for txn P189779109615997. Download PhonePe Business App: https://phon.pe/ppb'
            ]

In [ ]:
answers = ['debit','paytm_debit','phonepe_debit','credit','mobikwik_debit','phonepe_ credit','phonepe_cashbackcredit']

for example in examples:
    print(example,
          f'\nprediction = {model.predict([example]).argmax(axis=1)}',
          f'\nlabel = {answers[model.predict([example]).argmax(axis=1)[0]]}',
          '\n')
    

Dear Customer, your Account XX5605 has been debited with INR 4,700.00 on 11-Feb-19. Info: BIL*ONL*001640199809*Citiban. The Available Balance is INR 21,147.12.For dispute,call 04033667777. 
prediction = [0] 
label = debit 

Rs. 2.00 credited to a/c XXXXXX5024 on 16-04-21 by a/c linked to VPA goog-payment@okaxis (UPI Ref No  110620154923). 
prediction = [3] 
label = credit 

Acct XX605 debited with INR 12,159.00 on 04-Oct-19.Info: ACH*HDBFINANC.Avbl Bal:INR 1,02,356.71.Call 18002662 for dispute or SMS BLOCK 605 to 9215676766 
prediction = [0] 
label = debit 

Youve received Rs.88 cashback from PhonePe into your wallet for Get up to 100 Cashback. Flat 50 on first two transaction on IRCTC Android App.  Current cashback gift voucher balance is Rs.131 
prediction = [6] 
label = phonepe_cashbackcredit 

Rs. 234 transferred to 9730815322 at 2021-02-03 15:28:41. Updated Balance Rs. 646 For queries, visit http://m.p-y.tm/care  
prediction = [1] 
label = paytm_debit 

Paid Rs.434  to SANIKA chos

In [ ]:
# original_results = tf.sigmoid(model(tf.constant(examples)))
# def print_my_examples(inputs, results):
#   result_for_printing = \
#     [f'input: {inputs[i]:<30} : prediction: {results[i][0]}'
#                          for i in range(len(inputs))]
#   print(*result_for_printing, sep='\n')
#   print()


# print('Results from the model in memory:')
# print_my_examples(examples, original_results)